package Monopoly.GameSpaces;

public enum SpaceEffects {
	NEXT_RAILROAD, NEXT_UTILITY, GET_OUT_OF_JAIL_FREE,
	JAIL, BACK_THREE_SPACES, GO, BOARDWALK, ILLINOIS_AVENUE,
	ST_CHARLES_PLACE, READING_RAILROAD
}
